-- Normalized Database Structure for Harees
-- Generated by Antigravity
-- Date: 2025-12-22


SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


-- --------------------------------------------------------
-- 1. Reference Tables (Lookup Data)
-- --------------------------------------------------------

-- Categories: Replaces the "Table per Category" pattern
-- Now includes Pricing Logic (Making Charges) to simplify maintenance
CREATE TABLE `categories` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `parent_id` BIGINT UNSIGNED NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL UNIQUE,
  `description` TEXT NULL,
  
  -- Dynamic Pricing Configuration
  `making_charges` DECIMAL(10, 2) DEFAULT 0.00 COMMENT 'Value Addition (VA) amount or percentage',
  `making_charges_type` ENUM('percent', 'fixed') DEFAULT 'percent' COMMENT 'Is VA a percentage of gold rate or fixed amount?',
  `waste_percentage` DECIMAL(5, 2) DEFAULT 0.00 COMMENT 'Additional wastage charge if applicable',
  
  `is_active` TINYINT(1) DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`parent_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Metals: Gold, Silver, Platinum
CREATE TABLE `metals` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL UNIQUE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Metal Purities: 18K, 22K, 24K
CREATE TABLE `metal_purities` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `metal_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `purity_value` DECIMAL(6,4) NULL COMMENT 'e.g., 0.7500 for 18K',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`metal_id`) REFERENCES `metals`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Gold Rates: Daily rates for dynamic pricing
CREATE TABLE `gold_rates` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `metal_purity_id` INT UNSIGNED NOT NULL,
  `rate_per_gram` DECIMAL(10, 2) NOT NULL,
  `effective_date` DATE NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`metal_purity_id`) REFERENCES `metal_purities`(`id`) ON DELETE CASCADE,
  INDEX `idx_date_purity` (`effective_date`, `metal_purity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Suppliers
CREATE TABLE `suppliers` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `contact_info` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------
-- 2. Core Product Table
-- --------------------------------------------------------

-- Unified Product Table: Contains all products from all categories
CREATE TABLE `products` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  
  -- Basic Identification
  `product_code` VARCHAR(100) NOT NULL UNIQUE,
  `sku` VARCHAR(100) NULL UNIQUE,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL UNIQUE,
  `description` TEXT NULL,
  
  -- Classification
  `category_id` BIGINT UNSIGNED NULL,
  `metal_id` INT UNSIGNED NULL,
  `metal_purity_id` INT UNSIGNED NULL,
  `supplier_id` INT UNSIGNED NULL,
  
  -- Inventory & Status
  `stock_quantity` INT DEFAULT 0,
  `is_featured` TINYINT(1) DEFAULT 0,
  `is_visible` TINYINT(1) DEFAULT 1,
  `delist` TINYINT(1) DEFAULT 0,
  
  -- Detailed Specs (Physical)
  `gender` ENUM('Male','Female','Unisex','Kids') DEFAULT 'Unisex',
  `size` VARCHAR(100) NULL, -- Standardized size (e.g. Ring Size 12)
  `gross_weight` DECIMAL(10,5) NOT NULL DEFAULT 0.00000,
  `net_weight` DECIMAL(10,5) NULL,
  `product_model` VARCHAR(100) NULL,
  `manufacture_time` VARCHAR(100) NULL,
  
  -- Stone Information (Grouped for clarity, can be normalized further if needed)
  `stone_available` TINYINT(1) DEFAULT 0,
  `stone_desc` VARCHAR(255) NULL,
  `stone_color` VARCHAR(100) NULL,
  `stone_shape` VARCHAR(100) NULL,
  `stone_count` INT NULL,
  `stone_weight` DECIMAL(10,5) NULL,
  `stone_cost` DECIMAL(15,2) NULL,
  
  -- Diamond Information
  `diamond_available` TINYINT(1) DEFAULT 0,
  `dia_desc` TEXT NULL,
  `dia_cent` DECIMAL(10,5) NULL,
  `dia_count` INT NULL,
  `dia_cut` VARCHAR(100) NULL,
  `dia_color` VARCHAR(100) NULL,
  `dia_clarity` VARCHAR(100) NULL,
  `dia_shape` VARCHAR(100) NULL,
  
  -- Beads Information
  `beads_available` TINYINT(1) DEFAULT 0,
  `beads_desc` TEXT NULL,
  `beads_color` VARCHAR(100) NULL,
  `beads_count` INT NULL,
  `beads_weight` DECIMAL(10,5) NULL,
  `beads_cost` DECIMAL(15,2) NULL,
  
  -- Pearls Information
  `pearls_available` TINYINT(1) DEFAULT 0,
  `pearls_desc` TEXT NULL,
  `pearls_color` VARCHAR(100) NULL,
  `pearls_count` INT NULL,
  `pearls_weight` DECIMAL(10,5) NULL,
  `pearls_cost` DECIMAL(15,2) NULL,

  -- Pricing (Calculated dynamically, this is just for caching usually)
  `price` DECIMAL(15, 2) NULL COMMENT 'Cached calculated price. Real price = (GoldRate * Weight) + VA + StoneCost',
  
  -- SEO & Meta
  `search_keywords` TEXT NULL,
  `tags` TEXT NULL, -- CSV of tags or JSON
  
  -- Timestamps
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  -- Indexes for Performance
  INDEX `idx_category` (`category_id`),
  INDEX `idx_price` (`price`),
  INDEX `idx_search` (`name`),
  
  -- Foreign Keys
  FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`metal_id`) REFERENCES `metals`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`metal_purity_id`) REFERENCES `metal_purities`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`supplier_id`) REFERENCES `suppliers`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------
-- 3. Media Tables
-- --------------------------------------------------------

-- Product Images: Allows unlimited images per product
CREATE TABLE `product_images` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `image_path` VARCHAR(255) NOT NULL,
  `alt_text` VARCHAR(255) NULL,
  `sort_order` INT DEFAULT 0,
  `is_primary` TINYINT(1) DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

COMMIT;
